# Generated by Django 5.2.7 on 2025-10-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="forms",
            new_name="form",
        ),
    ]
