# Generated by Django 5.2.7 on 2025-10-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_rename_forms_submission_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="schema",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
